[project]
name = "tg-claude"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Maksim Kachynski", email = "max.kachinsky@rocketdata.io" }
]
requires-python = ">=3.12"
dependencies = [
    "aiogram>=3.31.0",
    "aiohttp>=3.14.3",
    "markdown-it-py>=4.2.0",
    "python-dotenv>=1.2.3",
]

[project.scripts]
tg-claude = "tg_claude:main"

[build-system]
requires = ["uv_build>=0.12.17,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
